version: '3'
services:
  web:
    build: ./nginx
    ports:
     - "8080:80"
  db:
    build: ./mysql
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
    - MYSQL_DATABASE=demodb
