version: '3'
services:
  db:
    build: ./mysql
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
    - MYSQL_DATABASE=demodb

  centos-openjdk:
    build:
      context: busybox
      dockerfile: Dockerfile
    image: parrotstream/centos-openjdk:latest
  web:
    build: ./nginx
    ports:
     - "8080:80"

